language: generic
sudo: enabled
install:
  - sudo add-apt-repository ppa:alexlarsson/flatpak -y
  - sudo apt-get update
  - while [ $(pgrep apt | wc -l) -ge 1 ]; do sleep 1 ; done
  - sudo apt-get install -y flatpak
  - wget https://flathub.org/repo/appstream/org.octave.Octave.flatpakref
  - sudo flatpak install -y org.octave.Octave.flatpakref

dist: xenial

script: flatpak run org.octave.Octave --no-gui --eval "addpath tests; RunAllTests;"
