language: generic
sudo: enabled
install:
  - sudo sed -i "s/xenial/disco/g" /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install -y octave octave-control

dist: xenial

notifications:
  email:
    - leo@robol.it
    - stefano.massei@epfl.ch

jobs:
  include:
    - stage: unit tests
      script: octave --no-gui --eval "pkg load control; addpath tests; hodlroption('compression', 'qr'); hssoption('compression', 'qr'); RunAllTests;"
    - stage_ unit tests
      script: octave --no-gui --eval "pkg load control; addpath tests; hodlroption('compression', 'svd'); hssoption('compression', 'svd'); RunAllTests;"
