language: generic
sudo: enabled
install:
  - sudo sed -i "s/xenial/cosmic/g" /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install -y octave octave-control

dist: xenial

notifications:
  email:
    - leo@robol.it
    - stefano.massei@epfl.ch

script: 
  - octave --no-gui --eval "pkg load control; addpath tests; RunAllTests;"
