language: generic
sudo: enabled
install:
  - sudo sed -i "s/xenial/disco/g" /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install -y octave octave-control

dist: xenial

notifications:
  email:
    - leo@robol.it
    - stefano.massei@epfl.ch

jobs:
  include:
    - name: "Unit Tests / HODLR / QR compression"
      stage: unit tests
      script: octave --no-gui --eval "pkg load control; addpath tests; hodlroption('compression', 'qr'); hodlr_RunAllTests;"
    - name: "Unit Tests / HODLR / SVD compression"
      stage: unit tests
      script: octave --no-gui --eval "pkg load control; addpath tests; hodlroption('compression', 'svd'); hodlr_RunAllTests;"
    - name: "Unit Tests / HSS / QR compression"
      stage: unit tests
      script: octave --no-gui --eval "pkg load control; addpath tests; hssoption('compression', 'qr'); hss_RunAllTests;"
    - name: "Unit Tests / HSS / SVD compression"
      stage: unit tests
      script: octave --no-gui --eval "pkg load control; addpath tests; hssoption('compression', 'svd'); hss_RunAllTests;"
    - name: "Unit Tests / HMATRIX / QR compression"
      stage: unit tests
      script: octave --no-gui --eval "pkg load control; addpath tests; hmatrixoption('compression', 'qr'); hmatrix_RunAllTests;"
    - name: "Unit Tests / HMATRIX / SVD compression"
      stage: unit tests
      script: octave --no-gui --eval "pkg load control; addpath tests; hmatrixoption('compression', 'svd'); hmatrix_RunAllTests;"
