# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  octave:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      OCTAVE: "flatpak run org.octave.Octave"
    steps:
      - uses: actions/checkout@v2
      - name: Install GNU/Octave
        run: |
          sudo apt-get update
          sudo apt-get -y install flatpak
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y org.octave.Octave
          ${OCTAVE} --eval "pkg install -forge io"
          ${OCTAVE} --eval "pkg install -forge statistics"
          ${OCTAVE} --eval "pkg install -forge control"
          echo "pkg load control" >> ~/.octaverc
          echo "pkg load statistics" >> ~/.octaverc
      - name: Run tests (QR compression)
        run: |
          ${OCTAVE} --no-gui --eval "addpath tests; hodlroption('compression', 'qr'); hssoption('compression', 'qr'); halroption('compression', 'qr'); RunAllTests;"
      - name: Run tests (SVD compression)
        run: |
          ${OCTAVE} --no-gui --eval "addpath tests; RunAllTests;"

  matlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0
      - name: Run tests (SVD compression)
        uses: matlab-actions/run-command@v0
        with:
          command: "addpath tests; RunAllTests"
      - name: Run tests (QR compression)
        uses: matlab-actions/run-command@v0
        with:
          command: "addpath tests; hodlrption('compression', 'qr'); hssoption('compression', 'qr'); halroption('compression', 'qr'); RunAllTests"

